// Code generated by protoc-gen-go.
// source: find_successor.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	find_successor.proto
	notify.proto

It has these top-level messages:
	FindSuccessorRequest
	FindSuccessorResponse
	NotifyRequest
	NotifyResponse
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FindSuccessorRequest struct {
	ID   string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *FindSuccessorRequest) Reset()                    { *m = FindSuccessorRequest{} }
func (m *FindSuccessorRequest) String() string            { return proto.CompactTextString(m) }
func (*FindSuccessorRequest) ProtoMessage()               {}
func (*FindSuccessorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *FindSuccessorRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *FindSuccessorRequest) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type FindSuccessorResponse struct {
	ID   string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Host string `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
}

func (m *FindSuccessorResponse) Reset()                    { *m = FindSuccessorResponse{} }
func (m *FindSuccessorResponse) String() string            { return proto.CompactTextString(m) }
func (*FindSuccessorResponse) ProtoMessage()               {}
func (*FindSuccessorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FindSuccessorResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *FindSuccessorResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func init() {
	proto.RegisterType((*FindSuccessorRequest)(nil), "protobuf.FindSuccessorRequest")
	proto.RegisterType((*FindSuccessorResponse)(nil), "protobuf.FindSuccessorResponse")
}

func init() { proto.RegisterFile("find_successor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x49, 0xcb, 0xcc, 0x4b,
	0x89, 0x2f, 0x2e, 0x4d, 0x4e, 0x4e, 0x2d, 0x2e, 0xce, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0xe2, 0x00, 0x53, 0x49, 0xa5, 0x69, 0x4a, 0x56, 0x5c, 0x22, 0x6e, 0x99, 0x79, 0x29, 0xc1,
	0x30, 0x05, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x7c, 0x5c, 0x4c, 0x9e, 0x2e, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x4c, 0x9e, 0x2e, 0x42, 0x42, 0x5c, 0x2c, 0x19, 0xf9, 0xc5,
	0x25, 0x12, 0x4c, 0x60, 0x11, 0x30, 0x5b, 0xc9, 0x9a, 0x4b, 0x14, 0x4d, 0x6f, 0x71, 0x41, 0x7e,
	0x5e, 0x71, 0x2a, 0x31, 0x9a, 0x93, 0xd8, 0xc0, 0x4e, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff,
	0xd9, 0x83, 0xbb, 0x43, 0xa1, 0x00, 0x00, 0x00,
}
